server:
  port: 8189
jwt:
  secret: 984hg493gh
  lifetime: 30m
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_security_test
      username: ilya
      password: ilya
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

#server:
#  port: 8189
#jwt:
#  secret: 984hg493gh
#  lifetime: 30m
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_security_test
#    username: new_user
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  main:
#    allow-circular-references: true


#server:
#  port: 8189
#jwt:
#  secret: 984hg493gh
#  lifetime: 30m
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./users1;MODE=PostgreSQL
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
#  main:
#    allow-circular-references: true


#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#    username: springuser
#    password: ThePassword
#    driver-class-name: com.mysql.cj.jdbc.Driver